name: Update Homebrew
on:
    push:
      paths:
        - '5etools-homebrew/Dungeon Church; Pyora.json'  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Update homebrew on DC server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: sudo ./home/ubuntu/5etools-homebrew/getbrew.sh