name: Update Pyora Homebrew
on:
  push:
    paths:
      - '5etools-homebrew/Dungeon Church; Pyora.json'
    branches:
      - main
jobs:
  remoteupdate:
    name: Update Pyora data on server
    runs-on: ubuntu-latest
    steps:
    - name: SSH to run script on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: sudo /home/ubuntu/5etools-homebrew/getbrew.sh