name: Update Homebrew
on:
    pull_request:
      types:
        - closed
      paths:
        - '5etools-homebrew/**.json'  
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Update homebrew on DC server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: sudo ./home/ubuntu/5etools-homebrew/getbrew.sh