name: Validate Homebrew JSON

on: [pull_request, push]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: ScratchAddons/validate-json-action@master
        env:
          schema: /.github/homebrew-schema.json
          jsons: |
            "5etools-homebrew/Dungeon Church; Pyora.json"