name: Validate 5eTools Homebrew JSON

on:
  push:

jobs:
  validate-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: validate
      uses: ammarlakis/action-ajv@master
      with:
        schema: .github/homebrew-schema.json
        data: 5etools-homebrew/*json
        allErrors: true