name: Validate 5eTools Homebrew JSON

on:
  push:

jobs:
  validate-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: validate
      run: |-
        npx --package=5etools-utils -c "test-json-brew '/5etools-homebrew/Dungeon Church; Pyora.json'"